#!/usr/bin/env python3
"""
Auto-add cheapest product stores to AutoshBotSRC
Generated by find_cheapest_products.py
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, 'AutoshBotSRC/AutoshBotSRC')

from database import add_shopify_site

# Cheapest products from working stores
STORES_TO_ADD = [
    {
        "url": "lowkeysanfrancisco.myshopify.com",
        "product_id": 7630374862925,
        "variant_id": 42468546805837,
        "price": 12.0,
        "title": "Psockadelic Socks - Gang Gang",
    },
    {
        "url": "my-merch-hub.myshopify.com",
        "product_id": 7981357301940,
        "variant_id": 44012493373620,
        "price": 5.0,
        "title": "ROCKINGHAM CARS & COFFEE RCC STICKER - 2 PACK",
    },
    {
        "url": "itsjvke.myshopify.com",
        "product_id": 9543714406690,
        "variant_id": 50666543579426,
        "price": 1.49,
        "title": "ShipAid Delivery Guarantee",
    },
    {
        "url": "pepper-spray-store.myshopify.com",
        "product_id": 8611329048808,
        "variant_id": 45602956247272,
        "price": 0.01,
        "title": "TEST",
    },
    {
        "url": "coldest-6011.myshopify.com",
        "product_id": 9266769428712,
        "variant_id": 47848455602408,
        "price": 1.0,
        "title": "Shipping Protection",
    },
    {
        "url": "bflo-gallery-gift-shop.myshopify.com",
        "product_id": 9099496390883,
        "variant_id": 47771558772963,
        "price": 17.99,
        "title": "Infant Gerber Buffalo Bills Gray Huddles & Cuddles Onesie",
    },
    {
        "url": "santamonica.myshopify.com",
        "product_id": 7940672749759,
        "variant_id": 43625152512191,
        "price": 1.99,
        "title": "Beach Balls",
    },
    {
        "url": "marigoldclothing.myshopify.com",
        "product_id": 8314184073353,
        "variant_id": 44829342892169,
        "price": 12.0,
        "title": "Socksmith QUILT PATTERN SOCK",
    },
    {
        "url": "weiners-ltd.myshopify.com",
        "product_id": 4344551604275,
        "variant_id": 31171309994035,
        "price": 0.4,
        "title": "NEW- Select Travel Toothbrush",
    },
    {
        "url": "sellwholesale.myshopify.com",
        "product_id": 8258306736294,
        "variant_id": 45688078860454,
        "price": 6.5,
        "title": "Thermometer Secret Safe to Hide Keys Outside or Other Valuables",
    },
    {
        "url": "big-sissy-gear.myshopify.com",
        "product_id": 8486948831385,
        "variant_id": 45577789735065,
        "price": 6.0,
        "title": "STOVE PIPE RING",
    },
    {
        "url": "clarks-dummy-account.myshopify.com",
        "product_id": 10217194520857,
        "variant_id": 51764853866777,
        "price": 9.97,
        "title": "Milwaukee 48-22-8062 Bin Set for PACKOUT™, 2pk",
    },
    {
        "url": "ford-employee-merchandise.myshopify.com",
        "product_id": 9062882803939,
        "variant_id": 47556852416739,
        "price": 6.99,
        "title": "Ford Mad Libs Childrens Activity Book",
    },
    {
        "url": "stanceworks-store.myshopify.com",
        "product_id": 8261535662238,
        "variant_id": 45397388034206,
        "price": 7.0,
        "title": "StanceWorks Woven Keytag",
    },
    {
        "url": "altitude-authentics.myshopify.com",
        "product_id": 7502317715531,
        "variant_id": 41955895115851,
        "price": 44.0,
        "title": "Colorado Avalanche Blanket Snuggie",
    },
    {
        "url": "carls-true-value.myshopify.com",
        "product_id": 10180745986349,
        "variant_id": 51702342451501,
        "price": 1.99,
        "title": "Ames 20\" Terracotta Riverland Planter",
    },
    {
        "url": "players-pickleball.myshopify.com",
        "product_id": 7462229246138,
        "variant_id": 42715727298746,
        "price": 5.0,
        "title": "Make a Donation to Trees for the Future",
    },
    {
        "url": "valenciakeydesigns.myshopify.com",
        "product_id": 9756988473627,
        "variant_id": 49662095425819,
        "price": 15.0,
        "title": "VALENCIA KEY Soft Clay Friendship/ Loveship Beaded Bracelets | WORTHY",
    },
    {
        "url": "kitross-los-angeles.myshopify.com",
        "product_id": 9260693553320,
        "variant_id": 55102845124776,
        "price": 11.95,
        "title": "FAUX FRECKLES NATURAL VIBES TATTOO",
    },
    {
        "url": "ymca-camp-takodah.myshopify.com",
        "product_id": 6228042580124,
        "variant_id": 37856402833564,
        "price": 3.0,
        "title": "Takodah Face Mask",
    },
    {
        "url": "maddesigns-shop.myshopify.com",
        "product_id": 8550699270302,
        "variant_id": 46279970783390,
        "price": 3.0,
        "title": "Strudel Sticker",
    },
    {
        "url": "cottonbear.myshopify.com",
        "product_id": 8550267912424,
        "variant_id": 45579033149672,
        "price": 1.0,
        "title": "LINK-1   Handmade Crochet Keychain/Figure",
    },
    {
        "url": "tileamerica.myshopify.com",
        "product_id": 7905522712610,
        "variant_id": 44643409756194,
        "price": 3.89,
        "title": "Deparisa Ceramic | While Supplies Last",
    },
    {
        "url": "shop-cain.myshopify.com",
        "product_id": 6807527227469,
        "variant_id": 39888636543053,
        "price": 5.0,
        "title": "Cain EP",
    },
    {
        "url": "fasterautokeys.myshopify.com",
        "product_id": 7415660052578,
        "variant_id": 42178896986210,
        "price": 16.95,
        "title": "4 Button Remote Key Shell with Remote Start for GMC 2010-2019",
    },
    {
        "url": "snappers-key-largo.myshopify.com",
        "product_id": 7147521015888,
        "variant_id": 41060685054032,
        "price": 2.79,
        "title": "Tallulah Decal",
    },
    {
        "url": "getpom-com.myshopify.com",
        "product_id": 9051793948958,
        "variant_id": 47892863877406,
        "price": 14.95,
        "title": "POM Runner Pepper Spray",
    },
    {
        "url": "exit-merch-and-apparel.myshopify.com",
        "product_id": 7747079405744,
        "variant_id": 44045378715824,
        "price": 4.0,
        "title": "Chatham HS Parking Permit Hologram Sticker",
    },
    {
        "url": "tigrlock.myshopify.com",
        "product_id": 4649317564460,
        "variant_id": 32631970168876,
        "price": 15.0,
        "title": "TIGR Bike Mounting Clip",
    },
    {
        "url": "mirmaru.myshopify.com",
        "product_id": 8404566114441,
        "variant_id": 45108695236745,
        "price": 8.5,
        "title": "BLACK American Bully Embroidered Pigment Dyed Cotton Baseball Cap",
    },
    {
        "url": "kieferauctionsupply.myshopify.com",
        "product_id": 11629286540,
        "variant_id": 45463299020,
        "price": 4.73,
        "title": "#55 Medium Chisel Tip Industrial Ink Markers",
    },
    {
        "url": "cdbucsshop.myshopify.com",
        "product_id": 8123277050047,
        "variant_id": 44268905922751,
        "price": 12.99,
        "title": "Miss Ashley Originals, Inc. Small Stacked w/Sheer Top",
    },
    {
        "url": "yahoolacreekbottoms.myshopify.com",
        "product_id": 7228822552709,
        "variant_id": 41475991666821,
        "price": 6.0,
        "title": "Itch Stick",
    },
    {
        "url": "votaw-tool.myshopify.com",
        "product_id": 5140490911879,
        "variant_id": 34494108369031,
        "price": 1.47,
        "title": "GREEN BACK THICK CLARINET PAD  9.0mm",
    },
    {
        "url": "southern-charm-baldwyn.myshopify.com",
        "product_id": 8610447884522,
        "variant_id": 45765902270698,
        "price": 10.0,
        "title": "Drop Earrings",
    },
    {
        "url": "fire-museum-of-houston.myshopify.com",
        "product_id": 9360855597285,
        "variant_id": 48067925180645,
        "price": 1.5,
        "title": "Decal - Pink Shield",
    },
    {
        "url": "amorepacificus.myshopify.com",
        "product_id": 6923988238438,
        "variant_id": 40386207481958,
        "price": 18.0,
        "title": "Bija Salicylic Spot Serum",
    },
    {
        "url": "charles-m-schulz-museum.myshopify.com",
        "product_id": 8258732622024,
        "variant_id": 44856956453064,
        "price": 1.0,
        "title": "Merry Christmas Postcard",
    },
    {
        "url": "untamed-natural-care.myshopify.com",
        "product_id": 8223562105028,
        "variant_id": 44734244487364,
        "price": 5.99,
        "title": "🌿 Evergreen Succulent – Vetiver & Bergamot",
    },
    {
        "url": "keytolife.myshopify.com",
        "product_id": 7964173369645,
        "variant_id": 44105995616557,
        "price": 4.0,
        "title": "Key to Kelp",
    },
    {
        "url": "charlotte-checkers.myshopify.com",
        "product_id": 8806833782939,
        "variant_id": 47666629509275,
        "price": 8.0,
        "title": "Charlotte Checkers Red-White Primary Cowbell",
    },
]

def add_all_stores():
    """Add all cheapest product stores to the bot database"""
    added = 0
    skipped = 0
    
    for store in STORES_TO_ADD:
        try:
            # Add store to database (assuming user_id=1 for now)
            if add_shopify_site(1, store['url']):
                print(f"✅ Added: {store['url']} - ${store['price']}")
                added += 1
            else:
                print(f"⚠️  Skipped: {store['url']} (already exists)")
                skipped += 1
        except Exception as e:
            print(f"❌ Error adding {store['url']}: {e}")
    
    print(f"\n📊 Summary: {added} added, {skipped} skipped")

if __name__ == '__main__':
    add_all_stores()
