#!/usr/bin/env python3
"""
Shopify Cheapest Products Scanner
Finds the cheapest products from all working Shopify stores and prepares them for bot integration
"""

import asyncio
import aiohttp
import json
import time
import random
from typing import List, Dict, Optional
import sys
import os

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from core.shopify_product_finder import DynamicProductFinder


class CheapestProductsScanner:
    """
    Scans all working Shopify stores to find their cheapest products
    """

    def __init__(self, max_concurrent: int = 10, timeout: int = 30):
        self.max_concurrent = max_concurrent
        self.timeout = timeout
        self.finder = DynamicProductFinder()
        self.results = []
        self.failed_stores = []

        # Load working stores
        self.working_stores = self.load_working_stores()

    def load_working_stores(self) -> List[str]:
        """Load working Shopify stores from file"""
        stores = []
        try:
            with open('working_shopify_stores.txt', 'r') as f:
                for line in f:
                    store = line.strip()
                    if store and not store.startswith('#'):
                        stores.append(store)
        except FileNotFoundError:
            print("❌ working_shopify_stores.txt not found")
            return []

        print(f"✅ Loaded {len(stores)} working stores")
        return stores

    async def scan_store(self, session: aiohttp.ClientSession, store_url: str) -> Optional[Dict]:
        """
        Scan a single store for its cheapest product
        """
        try:
            # Get cheapest product
            product = self.finder.get_cheapest_product(store_url)

            if product and product['available']:
                result = {
                    'store_url': store_url,
                    'product_id': product['product_id'],
                    'variant_id': product['variant_id'],
                    'title': product['title'],
                    'variant_title': product['variant_title'],
                    'price': product['price'],
                    'image': product['image'],
                    'scanned_at': time.time()
                }

                print(f"✅ {store_url}: ${product['price']} - {product['title'][:50]}...")
                return result
            else:
                print(f"⚠️  {store_url}: No available products found")
                return None

        except Exception as e:
            print(f"❌ {store_url}: {str(e)}")
            return None

    async def scan_all_stores(self) -> List[Dict]:
        """
        Scan all working stores concurrently
        """
        print(f"\n🔍 Starting scan of {len(self.working_stores)} stores...")
        print("=" * 80)

        semaphore = asyncio.Semaphore(self.max_concurrent)
        results = []

        async def scan_with_semaphore(store_url: str):
            async with semaphore:
                # Add random delay to avoid rate limiting
                await asyncio.sleep(random.uniform(0.1, 1.0))

                async with aiohttp.ClientSession(
                    timeout=aiohttp.ClientTimeout(total=self.timeout)
                ) as session:
                    result = await self.scan_store(session, store_url)
                    if result:
                        results.append(result)

        # Create tasks for all stores
        tasks = [scan_with_semaphore(store) for store in self.working_stores]

        # Execute with progress tracking
        completed = 0
        for coro in asyncio.as_completed(tasks):
            await coro
            completed += 1
            if completed % 50 == 0:
                print(f"📊 Progress: {completed}/{len(self.working_stores)} stores scanned")

        print(f"\n✅ Scan complete! Found {len(results)} stores with products")
        return results

    def save_results(self, results: List[Dict], filename: str = "cheapest_products.json"):
        """Save scan results to JSON file"""
        try:
            with open(filename, 'w') as f:
                json.dump(results, f, indent=2, default=str)
            print(f"💾 Results saved to {filename}")
        except Exception as e:
            print(f"❌ Failed to save results: {e}")

    def generate_bot_commands(self, results: List[Dict], filename: str = "add_cheapest_stores.py"):
        """Generate Python script to add all stores to the bot"""
        try:
            with open(filename, 'w') as f:
                f.write("#!/usr/bin/env python3\n")
                f.write('"""\n')
                f.write("Auto-add cheapest product stores to AutoshBotSRC\n")
                f.write("Generated by find_cheapest_products.py\n")
                f.write('"""\n\n')
                f.write("import sys\n")
                f.write("import os\n")
                f.write("sys.path.append(os.path.dirname(os.path.abspath(__file__)))\n")
                f.write("sys.path.insert(0, 'AutoshBotSRC/AutoshBotSRC')\n\n")
                f.write("from database import add_shopify_site\n\n")
                f.write("# Cheapest products from working stores\n")
                f.write("STORES_TO_ADD = [\n")

                for result in results:
                    store_url = result['store_url']
                    product_id = result['product_id']
                    variant_id = result['variant_id']
                    price = result['price']
                    title = result['title'].replace('"', '\\"')[:100]  # Escape quotes and limit length

                    f.write("    {\n")
                    f.write(f'        "url": "{store_url}",\n')
                    f.write(f'        "product_id": {product_id},\n')
                    f.write(f'        "variant_id": {variant_id},\n')
                    f.write(f'        "price": {price},\n')
                    f.write(f'        "title": "{title}",\n')
                    f.write("    },\n")

                f.write("]\n\n")
                f.write("def add_all_stores():\n")
                f.write('    """Add all cheapest product stores to the bot database"""\n')
                f.write("    added = 0\n")
                f.write("    skipped = 0\n")
                f.write("    \n")
                f.write("    for store in STORES_TO_ADD:\n")
                f.write("        try:\n")
                f.write("            # Add store to database (assuming user_id=1 for now)\n")
                f.write("            if add_shopify_site(1, store['url']):\n")
                f.write('                print(f"✅ Added: {store[\'url\']} - ${store[\'price\']}")\n')
                f.write("                added += 1\n")
                f.write("            else:\n")
                f.write('                print(f"⚠️  Skipped: {store[\'url\']} (already exists)")\n')
                f.write("                skipped += 1\n")
                f.write("        except Exception as e:\n")
                f.write('            print(f"❌ Error adding {store[\'url\']}: {e}")\n')
                f.write("    \n")
                f.write('    print(f"\\n📊 Summary: {added} added, {skipped} skipped")\n\n')
                f.write("if __name__ == '__main__':\n")
                f.write("    add_all_stores()\n")


        except Exception as e:
            print(f"❌ Failed to generate bot script: {e}")

    def print_summary(self, results: List[Dict]):
        """Print summary of scan results"""
        if not results:
            print("❌ No products found!")
            return

        print("\n" + "="*80)
        print("📊 SCAN SUMMARY")
        print("="*80)

        # Price distribution
        prices = [r['price'] for r in results]
        min_price = min(prices)
        max_price = max(prices)
        avg_price = sum(prices) / len(prices)

        print(f"🏪 Total stores with products: {len(results)}")
        print(f"💰 Price range: ${min_price:.2f} - ${max_price:.2f}")
        print(f"📊 Average price: ${avg_price:.2f}")
        print(f"🎯 Median price: ${sorted(prices)[len(prices)//2]:.2f}")

        # Price ranges
        ranges = [
            ("Free", 0, 0.01),
            ("$0.01-$1", 0.01, 1),
            ("$1-$5", 1, 5),
            ("$5-$10", 5, 10),
            ("$10-$25", 10, 25),
            ("$25+", 25, float('inf'))
        ]

        print("\n💰 Price Distribution:")
        for name, min_p, max_p in ranges:
            count = sum(1 for p in prices if min_p <= p < max_p)
            if count > 0:
                print(f"  {name}: {count} stores")

        # Top 10 cheapest
        print("\n🏆 Top 10 Cheapest Products:")
        sorted_results = sorted(results, key=lambda x: x['price'])
        for i, result in enumerate(sorted_results[:10], 1):
            print(f"{i:2d}. ${result['price']:.2f} - {result['title'][:50]}")

        print("="*80)


async def main():
    """Main execution function"""
    print("🛒 SHOPIFY CHEAPEST PRODUCTS SCANNER")
    print("="*80)

    # Initialize scanner
    scanner = CheapestProductsScanner(max_concurrent=20, timeout=30)

    if not scanner.working_stores:
        print("❌ No working stores found. Please ensure working_shopify_stores.txt exists.")
        return

    # Scan all stores
    start_time = time.time()
    results = await scanner.scan_all_stores()
    scan_time = time.time() - start_time

    # Print summary
    scanner.print_summary(results)

    # Save results
    scanner.save_results(results)

    # Generate bot integration script
    scanner.generate_bot_commands(results)

    print(f"\n⏱️  Total scan time: {scan_time:.1f} seconds")
    print(f"🎯 Ready to add {len(results)} stores to your bot!")


if __name__ == "__main__":
    # Run the scanner
    asyncio.run(main())
